name: ift6289-project-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - nltk
  - scikit-image
  - easydict
  - python-dateutil
  - tqdm
  - h5py
  - pytorch
  - torchfile
  - torchvision
  - tensorflow
